name: Release

on:
  push:
    branches: ["main"]
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Install GTK deps
      run: |
        pacman -S mingw-w64-ucrt-x86_64-gtk4 mingw-w64-ucrt-x86_64-python3-gobject mingw-w64-ucrt-x86_64-python3 mingw-w64-ucrt-x86_64-python-pip --noconfirm 

    - name: Install Poetry and Deps
      run: |
        python3 -m pip install --upgrade pip
        pip install poetry && poetry --version
        poetry install --with dev

    - name: Run Pyinstaller
      run: |
        poetry run pyinstaller --clean --onefile -w --add-data "data/style.css:./data" --exclude-module=pytest keyboard.py
        mv ./dist/keyboard

    - name: Store Dist
      uses: actions/upload-artifact@v4
      with:
        name: windows-dist
        path: dist/

  github-release:
    needs: [ build-windows ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: dist/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create "${{ github.ref_name }}" dist/**
          --repo "${{ github.repository }}"
          --generate-notes
