name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install GTK deps
      run: |
        sudo apt install libgirepository-1.0-dev libcairo2-dev gir1.2-gtk-4.0 -y

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ matrix.python-version }}

    - name: Install the dependencies
      run: uv sync --all-extras --dev


    - name: Run Pyinstaller
      run: |
        uv run pyinstaller keyboard.spec
        version=$(ldd --version | head -n 1 | awk '{print $NF}')
        pyversion=$(python --version 2>&1 | awk '{print $2}')
        mv ./dist/keyboard ./dist/virtual-keyboard-py$pyversion-glib$version-x86_64

    - name: Ruff Format/Lint
      run: |
        uv run ruff format --check
        uv run ruff check

    - name: Run Pytest
      run: |
        uv run coverage run -m pytest -v && uv run coverage report -m
